#!/usr/bin/env python3

import cgi
import os
import sqlite3
import json


def main():
    form = cgi.FieldStorage()
    new_vm_owner = form.getvalue("owner", "")
    new_vm_description = form.getvalue("description", "")
    okResponse()
    return

def okResponse():
    print("Status: 200 Ok")
    print("Content-Type: text/plain")
    print()
    print("Good connection")

main()




