#!/home/ubuntu/oci-env/bin/python3

import cgi
import os
import sqlite3
import json
import oci

from oci.config import from_file
from oci.config import validate_config

def main():

    config = oci.config.from_file(file_location="/home/ubuntu/.oci/config/oci_config")
    validate_config(config)

    form = cgi.FieldStorage()
    new_vm_owner = form.getvalue("owner", "")
    new_vm_description = form.getvalue("description", "")
    okResponse()
    return

def okResponse():
    print("Status: 200 Ok")
    print("Content-Type: text/plain")
    print()
    print("Pretty Good connection")

main()




